### ISSUE TITLE
It's not creating a Entity

### ISSUE THREAD

**Issue by SentryMax** [custom-components/sensor.mitemp_bt#10] opened 2019-12-03 12:48 UTC
Followed the guide and I'm running hassio, tried with and without the install bluez-hcidump and have restarted multiple times using the config provided on the integration page and still will not create a Entity. logs only show a warning about the integration "You are using a custom integration for mitemp_bt which has not been tested by Home Assistant...."
ps: can't use "name:" on configuration

**Comment by Magalex2x14** [comment] 2019-12-03 12:59
Which sensors do you use? If it’s not LYWSDCGQ (round body, segment LCD), then you need instal pre-release 0.4.0-beta (look my screenshots #8).

How far your sensors from HA host? You can temporary bring sensors closer, to exclude poor reception conditions.

**Comment by SentryMax** [comment] 2019-12-03 13:03
I'm using a LYWSDCGQ/01ZM (round body, segment LCD) that is set less than 3 meters from HA host.

**Comment by Magalex2x14** [comment] 2019-12-03 13:09
What is your hardware?

You can try to open shell and run commands from my instruction #7 to check if hcitool and hcidump work without problems.

**Comment by SentryMax** [comment] 2019-12-03 13:46
# sudo hcitool lescan --duplicates --passive
Set scan parameters failed: Input/output error
3 sudo hcidump --raw hci > dump.txt
sudo: hcidump: command not found

**Comment by Magalex2x14** [comment] 2019-12-03 14:29
`apt install bluez-hcidump`
`hcidump --duplicates`

**Comment by Magalex2x14** [comment] 2019-12-08 20:29
possibly same as #12

**Comment by Ernst79** [comment] 2019-12-22 09:28
@SentryMax the warning you mention in your opening post is normal. This warning is given for every custom component you have, and cannot be changed by us. 

Is your device running now, or do you still have issues? If it’s running ok, please close the issue

**Comment by vol4iniche** [comment] 2020-01-02 01:21
not looks like an issue, you could rename sensors in HA

**Comment by Uneo7** [comment] 2020-01-13 19:54
Hi I have the same issue (hte name thing I didn't tried). 
I installed the component through HACS and I'm running the latest 0.4.2-beta (the stable version doesn't work as well) on HassOS 3.7.

The component config is : 
```yaml
- platform: mitemp_bt
  rounding: True
  decimals: 2
  period: 60
  log_spikes: False
  use_median: False
  hcitool_active: True (I"ve tried with False, it doesn't change a thing)
```

I'm using two LYWSDCGQ the first one located less than a meter away from the Rpi and the second one at like 5m. Both have brand new batteries.

I'm collecting the debug logs with 
```
logger:
  default: warn
  logs:
    custom_components.mitemp_bt: debug
```

But I can't find anything unusual

```
2020-01-13 20:36:24 DEBUG (MainThread) [custom_components.mitemp_bt.sensor] No memory based tempdirs found! Falling back to /tmp (I d'ont care about ram storage ATM)
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] Starting
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] Start receiving broadcasts
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] update_ble called
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] Discovering Bluetooth LE devices
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] Stopping
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] Stop receiving broadcasts
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] Analyzing
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] reading hcidump...
2020-01-13 20:36:28 DEBUG (SyncWorker_18) [custom_components.mitemp_bt.sensor] Start receiving broadcasts
2020-01-13 20:37:29 DEBUG (SyncWorker_4) [custom_components.mitemp_bt.sensor] update_ble called
2020-01-13 20:37:29 DEBUG (SyncWorker_4) [custom_components.mitemp_bt.sensor] Discovering Bluetooth LE devices
2020-01-13 20:37:29 DEBUG (SyncWorker_4) [custom_components.mitemp_bt.sensor] Stopping```

Do you guys have any clue what's going on ?

**Comment by Magalex2x14** [comment] 2020-01-13 20:02
Try to run this command simultaneously with HA:
`hcidump --raw hci > dump.txt`
wait a minute or two, interrupt with CTRL+C and drop the dump.txt you got here. 
I'll see what's there...

**Comment by Uneo7** [comment] 2020-01-13 20:10
Hey,

Since I'm running HassIO I cannot run this command 😞 
HassIO is not a standard debian, it's custom made by the ha team.

**Comment by Magalex2x14** [comment] 2020-01-13 20:24
Yes, I have no experience with HassIO, but check out [this article](https://www.danielmartingonzalez.com/ssh-and-web-terminal-in-hassio/).
Apparently, it's time for me to try installing Hassio too - most of the issues come from its users ...

**Comment by Uneo7** [comment] 2020-01-13 20:33
I already have the ssh component installed and It's not working `hcidump: command not found`.
I had high hopes from this this modules (the embeded one kindda works when it wants to), keep me posted if you have new on this bug :)

**Comment by Magalex2x14** [comment] 2020-01-13 20:38
In our README.md it is indicated that paragraphs 1 and 2 of the HOW TO INSTALL section are not required for Hass.io, since there were feedback from its users that everything worked without it. Try to execute them. This week I will try to install fresh hassio, and see for myself what is there and how...

**Comment by Uneo7** [comment] 2020-01-13 20:48
Step 1. `Need apt, I cannot run it.`
Step 2. `setcap: command not found`

The terminal is very bare bone It's just running a busybox, we only get unix basics.

**Comment by Magalex2x14** [comment] 2020-01-13 20:53
OK. Give me a few days - I will let you know about my results.

**Comment by Magalex2x14** [comment] 2020-01-14 17:41
@Uneo7 from what I was able to read, nothing can be done with the combination of HASSio and HassOS. But I have not tried this type of installation. The fact is that after a little thought, I came to the conclusion that in my desire to help, I miss the root of the problem. And the root of the problem is that our component has a dependency that is not controlled by HomeAssistant at all. And this dependency cannot be satisfied manually on HassOS, as I understand it. Therefore, I think it is worthwhile to direct my efforts to force #9 , which should solve the problem with HassOS setup. Finding and implementing a solution will take some time (difficult to predict now). Have you thought about switching to another setup that gives more freedom? [Hassio on raspbian host + Docker](https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host) if you need Hassio or [python virtualenv setup](https://www.home-assistant.io/docs/installation/virtualenv/) on raspbian for "pure" Home Assistant.

**Comment by Uneo7** [comment] 2020-01-14 18:20
Hi, 

Thanks for taking the time to research this issue. 
I was thinking of switching for a few days already, I'm sick of having 0 control over HassOS.
I'll backup everything and use a good old debian with hassio :)

**Comment by Magalex2x14** [comment] 2020-01-14 19:27
@Uneo7 Just installed hassio:
Raspberry Pi 3 Model B and B+ 32bit (recommended) image
HassOS 3.8, Home Assistant 0.103.6
And you know what? Everything works out of the box...
No additional steps were required other than installing HACS.

**Comment by Magalex2x14** [comment] 2020-01-14 20:19
In order to test hcitool and hcidump, you must first follow the steps from this instruction: [Debugging Hass.io](https://developers.home-assistant.io/docs/en/hassio_debugging.html#hassos-based-hassio)
After that, access to the shell will appear, where you can check the operation of the hcitool and hcidump utilities.

**Comment by Magalex2x14** [comment] 2020-01-14 20:23
Despite all this, I still do not regret choosing virtualenv setup :)

**Comment by Uneo7** [comment] 2020-01-14 20:24
Sounds like a good place to find infos, I'll try that in a few hours. Just for finding what's going on, next step I switch to debian ^^

**Comment by Uneo7** [comment] 2020-01-14 22:16
Okay I've tried, it doesn't works (the server won't accept my key). At this point I don't care if it works or no fuck hassio, I'll install debian. I want my heaters automation back ^^

**Comment by Uneo7** [comment] 2020-01-14 23:39
@Magalex2x14 I've just installed Hassio on docker with debian and it's working just fine :)

https://i.uneo.me/images/FiuWer.png

I don't have the battery but honestly i don't care.
Thanks for taking the time to help me.

**Comment by Magalex2x14** [comment] 2020-01-15 17:11
Battery information is attribute of the sensor. If you need separate battery sensor, then you can create template sensor using the attribute as a source.

**Comment by Magalex2x14** [comment] 2020-01-22 19:51
[0.5.0](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.5.0-alfa) got rid of external utilities dependence. Please try it if the issue is relevant. Closing.

**Closed by Magalex2x14** 2020-01-22 19:51 UTC
