### ISSUE TITLE
New support Xiaomi Qinping Alarm Clock 

### ISSUE THREAD

**Issue by franck-outl4w** [custom-components/sensor.mitemp_bt#52] opened 2020-03-10 07:27 UTC
Hi, 
Given that it's a xiaomi bt device, that there are humidity and temperature sensor, I'd like to have it work with home assistant.
Following the how to, here is what I get in log:

2020-03-10 08:13:12 INFO (SyncWorker_19) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053a625950342d5808e2
[...]
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053a625950342d5808dd
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053a625950342d5808e2
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -31, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e1
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808dd
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e2
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -31, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e1
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e2
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e2
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -32, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e0
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e2
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808dd
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808dd
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e2
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -32, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e0
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808dd
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e2
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808dd
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808dd
2020-03-10 08:14:13 INFO (SyncWorker_12) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053c625950342d5808e2
[...]
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe305876053e625950342d5808dd
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e2902010000625950342d581d020106191695fe585876053f625950342d58658b10407e0000f19c270be2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e2902010000625950342d581d020106191695fe585876053f625950342d58658b10407e0000f19c270bdd
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -32, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e0
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808dd
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -33, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808df
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808dd
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808dd
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808dd
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -37, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808db
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -30, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e2
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -35, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808dd
2020-03-10 08:16:15 INFO (SyncWorker_1) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -31, MAC: 582D34505962, ADV: 043e1f02010000625950342d58130201060f1695fe3058760540625950342d5808e1

**Comment by Magalex2x14** [comment] 2020-03-10 12:58
Hello! Thanks for the log! Please tell us more about your sensor. What is this model?

I'll dig your log a little later. At first glance, there should not be any problems with its support, but I need information about the model.

**Comment by Magalex2x14** [comment] 2020-03-10 13:07
Oh, sorry, lost a little ) I see the issue title )

**Comment by Magalex2x14** [comment] 2020-03-10 13:10
This is a duplicate of #38

**Comment by franck-outl4w** [comment] 2020-03-10 13:23
I 

> 
> 
> This is a duplicate of #38

I saw that just before I read your replies :D thx

**Comment by Magalex2x14** [comment] 2020-03-10 15:42
@franck-outl4w please try `qinping-cgd1` branch
do not forget to fill in the encryptors option
This alarm clock (as well as LYWSD03) seems to send data quite rarely, so entities will not appear immediately (10 minutes in the case of LYWSD03)

If everything goes well, then I will uopdate the documentation and make a release

**Comment by franck-outl4w** [comment] 2020-03-10 16:26
I'll try to do this this evening

**Comment by Magalex2x14** [comment] 2020-03-10 22:41
closed as duplicate #38

**Closed by Magalex2x14** 2020-03-10 22:41 UTC
