### ISSUE TITLE
You shouldn't use deprecated bluez utilities

### ISSUE THREAD

**Issue by drizzt** [custom-components/sensor.mitemp_bt#9] opened 2019-12-02 16:35 UTC
Hi,
why are you using deprecated bluez utilities https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=b1eb2c4cd057624312e0412f6c4be000f7fc3617?

I suggest to use [dbus api](https://git.kernel.org/cgit/bluetooth/bluez.git/tree/doc/device-api.txt) directly instead of hcitool and btmon/btsnoop instead of hcidump.

This is a problem if you use home-assistant on Arch Linux

**Comment by Magalex2x14** [comment] 2019-12-02 16:48
Yes, we are aware of the situation. Initially, the component code was written that way, and as users (non-programmers) who picked up the idea of ​​the component, our first task was to understand the principle, debug it, and bring it to a stable usable state. More recently, it was a crude non-working gist. After the release of 0.4.0 with support for all (as far as I know) Xiaomi BLE sensors, I just planned to tackle the issue of obtaining data in a normal way.

**Comment by Magalex2x14** [comment] 2020-01-19 20:26
After some study of the available options, I come to the conclusion that the Bluez D-Bus is not very convenient for our task, since the scan implemented there returns a list of devices, which is inconvenient and it is not clear how to receive individual advertisements in this case. Currently, I am inclined to work with the HCI interface (which requires, however, the Python interpreter to have the appropriate rights).

**Comment by Magalex2x14** [comment] 2020-01-19 20:27
Please refute my conclusions if I am mistaken.

**Comment by aqualx** [comment] 2020-01-19 21:38
Quite a lot of python projects use bluetooth wrapper library [bluepy](https://github.com/IanHarvey/bluepy).
This library has class [Scanner](http://ianharvey.github.io/bluepy-doc/scanner.html) that according to description is exactly what we need.

PS: current solution doesn't work if system has more than one bluetooth controller because start of _hcitool_ simply fails :(

**Comment by Magalex2x14** [comment] 2020-01-20 14:52
@aqualx Yes, I saw this library, thanks. But I like [aioblescan](https://github.com/frawau/aioblescan) more (it gives more control over the scanning process and since we get all HCI-events, this will allow to "simulate" hcidump work, that is, at the initial stage, we will not need to deeply change the component code, and potentially makes it possible to catch a scan stop due to external interference or errors). If in the future we need another BT-functional, then we can look towards python-bluezero, which is based on aioblescan (scanning).

P.S. Can you explain what the problem is with multiple bt-controllers? The ability to specify the hci-interface in the component settings will solve the problem? Please, create new issue for this.

**Comment by aqualx** [comment] 2020-01-20 16:05
FYI: According to this [thread](https://github.com/IanHarvey/bluepy/issues/198) bluepy has passive scanning

**Comment by Magalex2x14** [comment] 2020-01-22 19:53
[0.5.0](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.5.0-alfa) got rid of deprecated utilities dependence. Closing.

**Closed by Magalex2x14** 2020-01-22 19:53 UTC
