### ISSUE TITLE
After upgrade to 0.6.4 HA does not start correctly

### ISSUE THREAD

**Issue by reaper7** [custom-components/sensor.mitemp_bt#63] opened 2020-04-12 14:46 UTC
After upgrade to 0.6.4 HA does not start correctly,
is shown in the list of processes (ps -ax) but the webinterface doesn't work
and there are no tips in the HA log :(

After restoring to version 0.6.3 everything works fine.

**Comment by Magalex2x14** [comment] 2020-04-12 15:36
Details are needed. What is in the HA log?
I'm fine on two systems (rpi 3b+ with Hassio, 0.107.7 and mac mini with HA 0.108.3,  python virtual env).

**Comment by Magalex2x14** [comment] 2020-04-12 15:37
Is the log completely empty?

**Comment by reaper7** [comment] 2020-04-12 15:53
how do i set the logger in configuration.yaml for sensor.mitemp_bt ?

My HA config:
```

arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
os_version | 4.19.97-v7+
python_version | 3.7.3
timezone | Europe/Warsaw
version | 0.108.3
virtualenv | true
```

**Comment by Magalex2x14** [comment] 2020-04-12 16:01
Our FAQ [describes](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#debug) how to enable debug mode for a component.

However, I think these actions will not lead to anything, because even if there is an error in the component code, HA should still start and make a log entry about why it failed to load the component. I suspect that you are facing a system-wide problem.

What is in the syslog?

**Comment by alesoft73** [comment] 2020-04-12 16:44
In my case, bluetooth after few minuts don't work, i return to 0.6.3.
I use hassio in vm machine...

**Comment by reaper7** [comment] 2020-04-12 16:49
however, the problem still exists, 
after rpi restart on 0.6.4, I can't connect to HA via the web interface :(

log:
```
2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for airly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for zigbee2mqtt_networkmap which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ups_pico which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for uilogs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-12 18:33:39 ERROR (MainThread) [homeassistant.components.sensor] The airly platform for the sensor integration does not support platform setup. Please remove it from your config.
2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] Starting
2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] Spawning HCIdump thread(s).
2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] HCIdump thread: Init
2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] HCIdump thread: Init finished
2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] Starting HCIdump thread for hci0
2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: Run
2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] HCIdump threads count = 1
2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] 0 encryptors mac:key pairs loaded.
2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: Connection
2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: Connected
2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: start main event_loop
2020-04-12 18:33:40 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] update_ble called
2020-04-12 18:33:40 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] First run, skip parsing.
```
and nothing more in logs for 10 minutes

SYSLOG:
```
Apr 12 18:33:03 rpi systemd[1]: Starting Home Assistant for pi...
Apr 12 18:33:04 rpi systemd[1]: Started Home Assistant for pi.
Apr 12 18:33:07 rpi hass[18065]: 2020-04-12 18:33:07 INFO (MainThread) [homeassistant.bootstrap] Config directory: /home/pi/.homeassistant
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_2) [homeassistant.loader] Loaded uilogs from custom_components.uilogs
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_1) [homeassistant.loader] Loaded hacs from custom_components.hacs
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_6) [homeassistant.loader] Loaded antistorm from custom_components.antistorm
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_3) [homeassistant.loader] Loaded mitemp_bt from custom_components.mitemp_bt
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_1) [homeassistant.loader] Loaded google_fit from custom_components.google_fit
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_10) [homeassistant.loader] Loaded rpi_power from custom_components.rpi_power
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_4) [homeassistant.loader] Loaded ups_pico from custom_components.ups_pico
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_13) [homeassistant.loader] Loaded nipca from custom_components.nipca
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_14) [homeassistant.loader] Loaded generic_hygrostat from custom_components.generic_hygrostat
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_5) [homeassistant.loader] Loaded meteoalarm_m from custom_components.meteoalarm_m
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_15) [homeassistant.loader] Loaded zigbee2mqtt_networkmap from custom_components.zigbee2mqtt_networkmap
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_4) [homeassistant.loader] Loaded airly from custom_components.airly
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_2) [homeassistant.loader] Loaded homeassistant from homeassistant.components.homeassistant
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (SyncWorker_6) [homeassistant.loader] Loaded persistent_notification from homeassistant.components.persistent_notifi
cation
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (MainThread) [homeassistant.setup] Setting up homeassistant
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant took 0.0 seconds.
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (MainThread) [homeassistant.setup] Setting up persistent_notification
Apr 12 18:33:14 rpi hass[18065]: 2020-04-12 18:33:14 INFO (MainThread) [homeassistant.setup] Setup of domain persistent_notification took 0.0 seconds.
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for airly which has not been tested by Hom
e Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_1) [homeassistant.loader] Loaded webhook from homeassistant.components.webhook
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_3) [homeassistant.loader] Loaded mqtt from homeassistant.components.mqtt
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_7) [homeassistant.loader] Loaded light from homeassistant.components.light
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_8) [homeassistant.loader] Loaded device_tracker from homeassistant.components.device_tracker
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_13) [homeassistant.loader] Loaded cast from homeassistant.components.cast
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_17) [homeassistant.loader] Loaded person from homeassistant.components.person
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for zigbee2mqtt_networkmap which has not b
een tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_10) [homeassistant.loader] Loaded group from homeassistant.components.group
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_1) [homeassistant.loader] Loaded camera from homeassistant.components.camera
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_14) [homeassistant.loader] Loaded shell_command from homeassistant.components.shell_command
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_5) [homeassistant.loader] Loaded utility_meter from homeassistant.components.utility_meter
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_3) [homeassistant.loader] Loaded history from homeassistant.components.history
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_15) [homeassistant.loader] Loaded system_health from homeassistant.components.system_health
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_7) [homeassistant.loader] Loaded ffmpeg from homeassistant.components.ffmpeg
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_13) [homeassistant.loader] Loaded frontend from homeassistant.components.frontend
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_8) [homeassistant.loader] Loaded conversation from homeassistant.components.conversation
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_17) [homeassistant.loader] Loaded counter from homeassistant.components.counter
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_16) [homeassistant.loader] Loaded sensor from homeassistant.components.sensor
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_10) [homeassistant.loader] Loaded ifttt from homeassistant.components.ifttt
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_4) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_18) [homeassistant.loader] Loaded input_boolean from homeassistant.components.input_boolean
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_5) [homeassistant.loader] Loaded coronavirus from homeassistant.components.coronavirus
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_2) [homeassistant.loader] Loaded http from homeassistant.components.http
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_9) [homeassistant.loader] Loaded python_script from homeassistant.components.python_script
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home
 Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_14) [homeassistant.loader] Loaded gios from homeassistant.components.gios
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_12) [homeassistant.loader] Loaded switch from homeassistant.components.switch
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_6) [homeassistant.loader] Loaded input_select from homeassistant.components.input_select
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_3) [homeassistant.loader] Loaded speedtestdotnet from homeassistant.components.speedtestdotnet
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_0) [homeassistant.loader] Loaded tts from homeassistant.components.tts
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_11) [homeassistant.loader] Loaded proximity from homeassistant.components.proximity
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_19) [homeassistant.loader] Loaded wwlln from homeassistant.components.wwlln
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_8) [homeassistant.loader] Loaded cloud from homeassistant.components.cloud
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_7) [homeassistant.loader] Loaded mobile_app from homeassistant.components.mobile_app
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_1) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_15) [homeassistant.loader] Loaded weather from homeassistant.components.weather
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_13) [homeassistant.loader] Loaded logger from homeassistant.components.logger
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_17) [homeassistant.loader] Loaded duckdns from homeassistant.components.duckdns
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_16) [homeassistant.loader] Loaded input_number from homeassistant.components.input_number
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_4) [homeassistant.loader] Loaded remote from homeassistant.components.remote
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_10) [homeassistant.loader] Loaded sun from homeassistant.components.sun
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ups_pico which has not been tested by
Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_7) [homeassistant.loader] Loaded stream from homeassistant.components.stream
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_8) [homeassistant.loader] Loaded recorder from homeassistant.components.recorder
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_2) [homeassistant.loader] Loaded logbook from homeassistant.components.logbook
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_9) [homeassistant.loader] Loaded scene from homeassistant.components.scene
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_18) [homeassistant.loader] Loaded panel_iframe from homeassistant.components.panel_iframe
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_11) [homeassistant.loader] Loaded config from homeassistant.components.config
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_15) [homeassistant.loader] Loaded map from homeassistant.components.map
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_19) [homeassistant.loader] Loaded websocket_api from homeassistant.components.websocket_api
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_1) [homeassistant.loader] Loaded automation from homeassistant.components.automation
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_14) [homeassistant.loader] Loaded zone from homeassistant.components.zone
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_12) [homeassistant.loader] Loaded discovery from homeassistant.components.discovery
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_5) [homeassistant.loader] Loaded vacuum from homeassistant.components.vacuum
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_3) [homeassistant.loader] Loaded script from homeassistant.components.script
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_0) [homeassistant.loader] Loaded system_log from homeassistant.components.system_log
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_6) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_17) [homeassistant.loader] Loaded notify from homeassistant.components.notify
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for uilogs which has not been tested by Ho
me Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_7) [homeassistant.loader] Loaded samsungtv from homeassistant.components.samsungtv
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_2) [homeassistant.loader] Loaded climate from homeassistant.components.climate
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_8) [homeassistant.loader] Loaded updater from homeassistant.components.updater
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_8) [homeassistant.loader] Loaded api from homeassistant.components.api
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_13) [homeassistant.loader] Loaded alexa from homeassistant.components.alexa
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_4) [homeassistant.loader] Loaded auth from homeassistant.components.auth
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_18) [homeassistant.loader] Loaded device_automation from homeassistant.components.device_automation
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_11) [homeassistant.loader] Loaded lovelace from homeassistant.components.lovelace
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_19) [homeassistant.loader] Loaded onboarding from homeassistant.components.onboarding
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (SyncWorker_14) [homeassistant.loader] Loaded search from homeassistant.components.search
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (MainThread) [homeassistant.bootstrap] Setting up {'logger', 'system_log'}
Apr 12 18:33:15 rpi hass[18065]: 2020-04-12 18:33:15 INFO (MainThread) [homeassistant.setup] Setting up logger
Apr 12 18:33:30 rpi hass[18065]: [7467ace8] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 ERROR (MainThread) [homeassistant.components.sensor] The airly platform for the sensor integration does not support platf
orm setup. Please remove it from your config.
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] Starting
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] Spawning HCIdump thread(s).
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] HCIdump thread: Init
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] HCIdump thread: Init finished
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] Starting HCIdump thread for hci0
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: Run
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] HCIdump threads count = 1
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] 0 encryptors mac:key pairs loaded.
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: Connection
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: Connected
Apr 12 18:33:39 rpi hass[18065]: 2020-04-12 18:33:39 DEBUG (Thread-3) [custom_components.mitemp_bt.sensor] HCIdump thread: start main event_loop
Apr 12 18:33:40 rpi hass[18065]: 2020-04-12 18:33:40 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] update_ble called
Apr 12 18:33:40 rpi hass[18065]: 2020-04-12 18:33:40 DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] First run, skip parsing.
```

**Comment by alesoft73** [comment] 2020-04-12 16:56
Edit your configuration.yaml with ssh or samba and disable the configuration....after  restart.

**Comment by Magalex2x14** [comment] 2020-04-12 17:34
Everything looks good in your log (regarding the work of custom.mitemp_bt). The component setting up correctly and its first start finishes with the "First run, skip parsing" entry. After that, control is transferred to the HA core, which should start the component code again after the time specified in the `period` option has expired, but for some reason, this does not happen.

However, I see errors in your journal that are not related to the operation of the component discussed here. If I were you, I would first solve these problems. Then I would check the configuration file for extra spaces or tabs. It is also worth making sure that there is free space on the disk.

**Comment by DendelX** [comment] 2020-04-13 08:08
Problems here too, running hassio in docker with ubuntu machine. 0.6.3 works fine, but 0.6.4 don't load data. Hassio starts fine but sensor keeps unavailable. Return to 0.6.3 and works fine again.

**Comment by alexit84** [comment] 2020-04-13 09:15
Same here: hassio with RPI 4

**Comment by Magalex2x14** [comment] 2020-04-13 09:32
I can’t reproduce the problem.
I see no other way out than a step-by-step rollback of the changes made in 0.6.4.

Can anyone try to comment out line 127 in the file `sensor.py`:
```python
btctrl.send_command(aiobs.HCI_Cmd_Reset())
```
to
```python
#btctrl.send_command(aiobs.HCI_Cmd_Reset())
```
and restart HA?

**Comment by reaper7** [comment] 2020-04-13 09:33
@Magalex2x14 - I don't change the configuration, is still the same.
The only thing that changes is this component.
Free disk space is also adequate:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        28G   21G  5.8G  78% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   36M  428M   8% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
tmpfs           320M  800K  320M   1% /tmp
tmpfs            30M     0   30M   0% /var/tmp
tmpfs            80M  4.3M   76M   6% /var/log
/dev/sda6        69M   53M   17M  77% /boot
tmpfs            93M     0   93M   0% /run/user/1000

```

**Comment by Magalex2x14** [comment] 2020-04-13 09:35
@reaper7 Yes, too many people came up with a problem - something is wrong.
If possible, then try the change from my previous post.

**Comment by reaper7** [comment] 2020-04-13 09:47
with line 127 commented my HA starts properly,
readings from LYWSDCGQ are also good.

**Comment by thawizard** [comment] 2020-04-13 11:26
> Problems here too, running hassio in docker with ubuntu machine. 0.6.3 works fine, but 0.6.4 don't load data. Hassio starts fine but sensor keeps unavailable. Return to 0.6.3 and works fine again.

Got the same nuc/ubuntu/docker hassio.. 0.6.4 showing all sensors as unavailable. going back to 0.6.3 works fine again.

**Comment by Magalex2x14** [comment] 2020-04-13 11:58
> with line 127 commented my HA starts properly,
readings from LYWSDCGQ are also good.

@reaper7 Thank you!

Can anyone else try the suggestion from [this post](https://github.com/custom-components/sensor.mitemp_bt/issues/63#issuecomment-612828056)?

**Comment by stast1** [comment] 2020-04-13 12:02
I tried. Works.

**Comment by Magalex2x14** [comment] 2020-04-13 12:05
Very strange... OK. Soon I will release 0.6.5 with the rollback of this change.

**Comment by Magalex2x14** [comment] 2020-04-13 12:16
[0.6.5](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.6.5)

Who had the problems described above - please update

**Comment by stast1** [comment] 2020-04-13 12:32
Yes, now everything is working well.

**Comment by reaper7** [comment] 2020-04-13 13:30
0.6.5 works for me too.

@Magalex2x14 - please close this issue if is no longer needed.

**Comment by Magalex2x14** [comment] 2020-04-13 13:32
👍Feel free to reopen, if needed.

**Closed by Magalex2x14** 2020-04-13 13:32 UTC
